<?php

namespace App\Services\Exports;

use App\Models\CommissionRun;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CommissionReportExportService
{
    public function pdf(CommissionRun $run, Request $request): string
    {
        $pdf = new SimplePdfDocument();
        $lines = [];
        $lines[] = 'TikTok Affiliate Commission Report';
        $lines[] = 'Period: '.$this->period($run).' | Status: '.Str::headline($run->status);
        $lines[] = 'Generated: '.now()->format('Y-m-d H:i:s').' | Generated by: '.$request->user()->name;
        $lines[] = 'Filtered View: '.$this->filterLabel($request);
        $lines[] = 'Total Sales: RM '.number_format((float) $run->total_sales, 2).' | Total Commission: RM '.number_format((float) $run->total_commission, 2);
        $lines[] = 'Total Affiliates: '.$this->filteredSummaryQuery($run, $request)->count().' | Total Orders: '.$this->totalOrders($run);
        $lines[] = str_repeat('-', 150);
        $lines[] = $this->fixedRow(['Affiliate', 'Code', 'Group', 'Type', 'Sales', 'Personal', 'Mgr', 'L1', 'L2', 'L3', 'Total'], [24, 10, 12, 9, 12, 10, 10, 10, 10, 10, 12]);
        $lines[] = str_repeat('-', 150);

        foreach ($this->filteredSummaryQuery($run, $request)->orderBy('affiliate_name')->cursor() as $row) {
            $lines[] = $this->fixedRow([
                $row->affiliate_name,
                $row->affiliate_code ?: '-',
                $row->group_name ?: '-',
                $row->affiliate_type === 'external' ? 'Luar' : 'Inhouse',
                number_format((float) $row->total_sales, 2),
                number_format((float) $row->personal, 2),
                number_format((float) $row->manager_bonus, 2),
                number_format((float) $row->l1_earnings, 2),
                number_format((float) $row->l2_earnings, 2),
                number_format((float) $row->l3_earnings, 2),
                number_format((float) $row->total, 2),
            ], [24, 10, 12, 9, 12, 10, 10, 10, 10, 10, 12]);

            if (count($lines) >= 45) {
                $pdf->addPage($lines, $this->period($run));
                $lines = [];
            }
        }

        if ($lines !== []) {
            $pdf->addPage($lines, $this->period($run));
        }

        return $pdf->output();
    }

    public function excelPath(CommissionRun $run, Request $request): string
    {
        $path = storage_path('app/exports/commission-report-'.$run->year.'-'.$run->month.'-'.Str::random(8).'.xls');
        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0777, true);
        }

        $writer = new SpreadsheetXmlWriter($path);
        $writer->startSheet('Report Summary');
        foreach ([
            ['Period', $this->period($run)],
            ['Status', Str::headline($run->status)],
            ['Total Sales', (float) $run->total_sales],
            ['Total Commission', (float) $run->total_commission],
            ['Total Affiliates', $this->filteredSummaryQuery($run, $request)->count()],
            ['Total Orders', $this->totalOrders($run)],
            ['Generated At', now()->format('Y-m-d H:i:s')],
            ['Generated By', $request->user()->name],
            ['Filter', $this->filterLabel($request)],
        ] as $row) {
            $writer->row($row);
        }
        $writer->endSheet();

        $writer->startSheet('Affiliate Income Summary');
        $writer->row(['Affiliate Name', 'Affiliate Code', 'Group', 'Type', 'Total Sales', 'Personal', 'Manager Bonus', 'L1 Earnings', 'L2 Earnings', 'L3 Earnings', 'Total Commission']);
        foreach ($this->filteredSummaryQuery($run, $request)->orderBy('affiliate_name')->cursor() as $row) {
            $writer->row([
                $row->affiliate_name,
                $row->affiliate_code,
                $row->group_name,
                $row->affiliate_type === 'external' ? 'Affiliate Luar' : 'Inhouse',
                (float) $row->total_sales,
                (float) $row->personal,
                (float) $row->manager_bonus,
                (float) $row->l1_earnings,
                (float) $row->l2_earnings,
                (float) $row->l3_earnings,
                (float) $row->total,
            ]);
        }
        $writer->endSheet();

        $writer->startSheet('Commission Entry Details');
        $writer->row(['Receiver', 'Source Affiliate', 'Commission Type', 'Order ID', 'Rate', 'Base Amount', 'Commission Earned', 'Period']);
        DB::table('commission_entries')
            ->leftJoin('affiliates as receivers', 'receivers.id', '=', 'commission_entries.receiver_affiliate_id')
            ->leftJoin('affiliates as sources', 'sources.id', '=', 'commission_entries.source_affiliate_id')
            ->leftJoin('tiktok_orders', 'tiktok_orders.id', '=', 'commission_entries.tiktok_order_id')
            ->where('commission_entries.commission_run_id', $run->id)
            ->select([
                'commission_entries.id',
                'receivers.name as receiver_name',
                'sources.name as source_name',
                'commission_entries.commission_type',
                'tiktok_orders.order_id',
                'commission_entries.rate',
                'commission_entries.base_amount',
                'commission_entries.commission_amount',
            ])
            ->orderBy('commission_entries.id')
            ->chunkById(1000, function ($entries) use ($writer, $run): void {
                foreach ($entries as $entry) {
                    $writer->row([
                        $entry->receiver_name,
                        $entry->source_name,
                        Str::headline($entry->commission_type),
                        $entry->order_id ?: '-',
                        (float) $entry->rate,
                        (float) $entry->base_amount,
                        (float) $entry->commission_amount,
                        $this->period($run),
                    ]);
                }
            }, 'commission_entries.id', 'id');
        $writer->endSheet();
        $writer->close();

        return $path;
    }

    public function filteredSummaryQuery(CommissionRun $run, Request $request)
    {
        $group = trim((string) $request->query('summary_group', ''));
        $affiliate = $request->filled('summary_affiliate') ? $request->integer('summary_affiliate') : null;

        return $this->summaryQuery($run->id)
            ->when($group !== '', fn ($query) => $query->where('affiliates.group_name', $group))
            ->when($affiliate, fn ($query) => $query->where('affiliates.id', $affiliate));
    }

    private function summaryQuery(int $commissionRunId)
    {
        $salesSubquery = DB::table('commission_entries')
            ->select('source_affiliate_id', DB::raw('SUM(base_amount) as total_sales'))
            ->where('commission_run_id', $commissionRunId)
            ->where('commission_type', 'personal')
            ->groupBy('source_affiliate_id');

        return DB::table('commission_entries')
            ->join('affiliates', 'affiliates.id', '=', 'commission_entries.receiver_affiliate_id')
            ->leftJoinSub($salesSubquery, 'sales', fn ($join) => $join->on('sales.source_affiliate_id', '=', 'affiliates.id'))
            ->where('commission_entries.commission_run_id', $commissionRunId)
            ->groupBy('affiliates.id', 'affiliates.name', 'affiliates.affiliate_code', 'affiliates.group_name', 'affiliates.affiliate_type', 'sales.total_sales')
            ->select([
                'affiliates.id as affiliate_id',
                'affiliates.name as affiliate_name',
                'affiliates.affiliate_code',
                'affiliates.group_name',
                'affiliates.affiliate_type',
                DB::raw('COALESCE(sales.total_sales, 0) as total_sales'),
                DB::raw("SUM(CASE WHEN commission_entries.commission_type = 'personal' THEN commission_entries.commission_amount ELSE 0 END) as personal"),
                DB::raw("SUM(CASE WHEN commission_entries.commission_type = 'manager_bonus' THEN commission_entries.commission_amount ELSE 0 END) as manager_bonus"),
                DB::raw("SUM(CASE WHEN commission_entries.commission_type IN ('l1_overriding', 'l1_split_seller', 'l1_split_upline') OR (commission_entries.commission_type = 'overriding' AND commission_entries.level = 1) THEN commission_entries.commission_amount ELSE 0 END) as l1_earnings"),
                DB::raw("SUM(CASE WHEN commission_entries.commission_type = 'l2_overriding' OR (commission_entries.commission_type = 'overriding' AND commission_entries.level = 2) THEN commission_entries.commission_amount ELSE 0 END) as l2_earnings"),
                DB::raw("SUM(CASE WHEN commission_entries.commission_type = 'l3_overriding' OR (commission_entries.commission_type = 'overriding' AND commission_entries.level = 3) THEN commission_entries.commission_amount ELSE 0 END) as l3_earnings"),
                DB::raw('SUM(commission_entries.commission_amount) as total'),
            ]);
    }

    private function totalOrders(CommissionRun $run): int
    {
        return DB::table('commission_entries')
            ->where('commission_run_id', $run->id)
            ->whereNotNull('tiktok_order_id')
            ->distinct('tiktok_order_id')
            ->count('tiktok_order_id');
    }

    private function period(CommissionRun $run): string
    {
        return date('F', mktime(0, 0, 0, $run->month, 1)).' '.$run->year;
    }

    private function filterLabel(Request $request): string
    {
        $parts = array_filter([
            $request->query('summary_group') ? 'Group: '.$request->query('summary_group') : null,
            $request->query('summary_affiliate') ? 'Affiliate ID: '.$request->query('summary_affiliate') : null,
        ]);

        return $parts === [] ? 'Full affiliate summary' : implode('; ', $parts);
    }

    private function fixedRow(array $values, array $widths): string
    {
        return collect($values)->map(function ($value, $index) use ($widths): string {
            $value = mb_substr((string) $value, 0, $widths[$index] - 1);

            return str_pad($value, $widths[$index]);
        })->implode(' ');
    }
}
