<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Affiliate Login Access Report</title>
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; background: #f1f5f9; color: #0f172a; font-family: Arial, sans-serif; font-size: 10pt; }
        .page { max-width: 1320px; margin: 24px auto; background: #fff; padding: 24px; box-shadow: 0 1px 4px rgba(15, 23, 42, .12); }
        .actions { display: flex; justify-content: flex-end; gap: 8px; margin-bottom: 16px; }
        .button { display: inline-block; border: 1px solid #cbd5e1; border-radius: 6px; background: #fff; color: #334155; padding: 9px 14px; text-decoration: none; font-weight: 700; cursor: pointer; }
        .button-primary { border-color: #047857; background: #047857; color: #fff; }
        .report-header { display: flex; justify-content: space-between; gap: 24px; border-bottom: 3px solid #047857; padding-bottom: 14px; }
        h1 { margin: 4px 0 0; font-size: 20pt; }
        .system-title { color: #047857; font-size: 10pt; font-weight: 800; text-transform: uppercase; }
        .meta { min-width: 320px; font-size: 9pt; line-height: 1.6; }
        .meta strong { display: inline-block; min-width: 110px; }
        .warning { margin: 16px 0; border: 1px solid #f59e0b; background: #fffbeb; color: #92400e; padding: 10px 12px; font-weight: 800; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        th, td { border: 1px solid #94a3b8; padding: 7px; vertical-align: top; overflow-wrap: anywhere; }
        th { background: #e2e8f0; color: #0f172a; font-size: 8.5pt; text-align: left; }
        td { font-size: 8.5pt; line-height: 1.35; }
        .number { width: 4%; text-align: center; }
        .name { width: 28%; }
        .group { width: 12%; }
        .type { width: 10%; }
        .tiktok { width: 22%; }
        .login { width: 12%; }
        .password { width: 12%; font-family: Consolas, monospace; font-weight: 700; }
        .badge { display: inline-block; border-radius: 999px; padding: 2px 7px; font-size: 7.5pt; font-weight: 800; }
        .badge-amber { border: 1px solid #fcd34d; background: #fffbeb; color: #92400e; }
        .badge-green { border: 1px solid #a7f3d0; background: #ecfdf5; color: #065f46; }
        .muted { color: #64748b; }
        .empty { padding: 28px; text-align: center; color: #64748b; }
        @media print {
            body { background: #fff; }
            .no-print { display: none !important; }
            .page { max-width: none; margin: 0; padding: 0; box-shadow: none; }
            @page { size: A4 landscape; margin: 10mm; }
            thead { display: table-header-group; }
            tr { break-inside: avoid; page-break-inside: avoid; }
        }
    </style>
</head>
<body>
    <main class="page">
        <div class="actions no-print">
            <a href="{{ route('admin.affiliates.index', request()->only(['group', 'type', 'status', 'search'])) }}" class="button">Back to Affiliate Management</a>
            <button type="button" class="button button-primary" onclick="window.print()">Print / Save as PDF</button>
        </div>

        <header class="report-header">
            <div>
                <div class="system-title">TikTok Affiliate Commission System</div>
                <h1>Affiliate Login Access Report</h1>
            </div>
            <div class="meta">
                <div><strong>Generated:</strong> {{ $generatedAt->format('d/m/Y H:i:s') }}</div>
                <div><strong>Generated by:</strong> {{ $generatedBy->name }}</div>
                <div><strong>Group:</strong> {{ $filters['group'] ?? 'All Groups' }}</div>
                <div><strong>Type:</strong> {{ isset($filters['type']) ? ($filters['type'] === 'online' ? 'Online' : 'Inhouse') : 'All Types' }}</div>
                <div><strong>Search:</strong> {{ $filters['search'] ?? '-' }}</div>
                <div><strong>Total listed:</strong> {{ number_format($affiliates->count()) }}</div>
            </div>
        </header>

        <div class="warning">CONFIDENTIAL - Contains temporary login credentials. Keep securely and destroy after distribution.</div>

        <table>
            <thead>
                <tr>
                    <th class="number">No.</th>
                    <th class="name">Affiliate Name</th>
                    <th class="group">Group</th>
                    <th class="type">Type</th>
                    <th class="tiktok">TikTok Account(s)</th>
                    <th class="login">Login ID</th>
                    <th class="password">Temporary Password</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($affiliates as $affiliate)
                    @php
                        $isExternal = $affiliate->affiliate_type === 'online';
                        $email = $affiliate->user?->email;
                        $loginId = ! $affiliate->user
                            ? 'No login access'
                            : (($email && ! str_ends_with($email, '.local')) ? $email : ($affiliate->affiliate_code ?: $affiliate->user->affiliate_code));
                    @endphp
                    <tr>
                        <td class="number">{{ $loop->iteration }}</td>
                        <td class="name"><strong>{{ $affiliate->name }}</strong></td>
                        <td class="group">{{ $affiliate->group_name ?: '-' }}</td>
                        <td class="type">
                            @if ($isExternal)
                                <span class="badge badge-amber">Online</span>
                            @else
                                <span class="badge badge-green">Inhouse</span>
                            @endif
                        </td>
                        <td class="tiktok">
                            {{ $affiliate->tiktokAccounts->pluck('username_normalized')->filter()->join(', ') ?: '-' }}
                        </td>
                        <td class="login">{{ $loginId ?: '-' }}</td>
                        <td class="password">
                            {{ $credentials[$affiliate->id] ?? 'Not generated' }}
                        </td>
                    </tr>
                @empty
                    <tr><td colspan="7" class="empty">No affiliates match the selected report filters.</td></tr>
                @endforelse
            </tbody>
        </table>
    </main>
</body>
</html>
